version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: questions
      POSTGRES_USER: questions
      POSTGRES_PASSWORD: jmXzj3eV#
    ports:
      - "5432:5432"
    volumes:
      - ./local_pgdata:/var/lib/postgresql/data
